# Generated by Django 3.0.1 on 2020-01-15 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.FileField(upload_to='recipe-images/')),
                ('thumbnail', models.FileField(upload_to='recipe-thumbs/')),
                ('amount_persons', models.PositiveSmallIntegerField()),
                ('cook_time_minutes', models.PositiveSmallIntegerField()),
                ('instructions', models.CharField(max_length=4096)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomnom.Tag_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe', models.ManyToManyField(to='nomnom.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='nomnom.Tag'),
        ),
        migrations.CreateModel(
            name='IngredientSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(max_length=16)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomnom.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomnom.Recipe')),
            ],
        ),
    ]
