# Generated by Django 3.0.1 on 2020-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
