# Generated by Django 3.0.1 on 2020-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0008_auto_20200331_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientset',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredientset',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
