# Generated by Django 3.0.1 on 2020-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0009_auto_20200414_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientset',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredientset',
            name='unit',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
