# Generated by Django 3.0.1 on 2020-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0012_auto_20200414_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.CharField(max_length=256),
        ),
    ]
