version: "3"
services:

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./database:/var/lib/postgresql/data/


  nomnom_backend:
    image: tluderer/nomnomserver:latest-arm64
    environment:
      POSTGRES_HOST: db
      DOCKER_CONTAINER: 1
    # build: .
    restart: always
    ports:
      - "8100:8100"
    depends_on: 
      - db
    volumes: 
      - ./nomnom-config:/opt/app/config

# volumes:
#   database:
#   nomnom-config: