version: "3"
services:

  db:
    image: postgres:12.2
    expose: 
      - 5435
    volumes: 
      - pg_data:/var/lib/postgresql/pg_data
      - pg_backups:/pg_backups
    environment: 
      - POSTGRES_USER=nomnom
      - POSTGRES_PASSWORD=admin

  nomnom_api:
    build: .
    ports:
      - "8100:8001"
    depends_on: 
      - db

volumes:
  pg_data: {}
  pg_backups: {}