version: "3"
services:

  db:
    image: postgres
    restart: always
    expose: 
      - 5432
    environment: 
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./database:/var/lib/postgresql/12/main/


  nomnom_backend:
    image: tluderer/nomnomserver:latest-arm64
    restart: always
    ports:
      - "8100:8100"
    depends_on: 
      - db
    volumes: 
      - ./nomnom-config:/opt/app/config

volumes:
  database:
  nomnom-config: