# Generated by Django 3.0.1 on 2020-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0005_auto_20200125_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientset',
            name='unit',
            field=models.CharField(max_length=32),
        ),
    ]
