# Generated by Django 3.0.1 on 2020-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0014_auto_20200611_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(),
        ),
    ]
