# Generated by Django 3.0.1 on 2020-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0015_auto_20200611_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_thumbnail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
